export const mockRecipes ={
    recipes: [
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 24,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 3,
        healthScore: 12,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 260.37,
        extendedIngredients: [Array],
        id: 652825,
        title: 'My Asian Calamari',
        readyInMinutes: 45,
        servings: 4,
        sourceUrl: 'https://www.foodista.com/recipe/T64CXDRZ/my-asian-calamari',
        image: 'https://img.spoonacular.com/recipes/652825-556x370.jpg',
        imageType: 'jpg',
        summary: `My Asian Calamari requires around <b>45 minutes</b> from start to finish. Watching your figure? This dairy free and pescatarian recipe has <b>563 calories</b>, <b>24g of protein</b>, and <b>5g of fat</b> per serving. For <b>$2.6 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. This recipe is typical of Asian cuisine. A mixture of all spice powder, cornstarch, squid rings, and a handful of other ingredients are all it takes to make this recipe so delicious. 3 people have made this recipe and would make it again. It works well as a rather inexpensive hor d'oeuvre. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 59%</b>, which is solid. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/asian-calamari-salad-586727">Asian Calamari Salad</a>, <a href="https://spoonacular.com/recipes/southeast-asian-rice-noodles-with-calamari-and-herbs-188585">Southeast Asian Rice Noodles with Calamari and Herbs</a>, and <a href="https://spoonacular.com/recipes/christmas-eve-calamari-calamari-in-umido-per-la-vigilia-di-natale-597284">Christmas Eve Calamari | Calamari in Umido per la Vigilia di Natale</a>.`,
        cuisines: [Array],
        dishTypes: [Array],
        diets: [Array],
        occasions: [],
        instructions: "<ol><li>In a bowl mix the ff: salt, sugar, pepper,egg white, curry powder,all spice and cornstarch.</li><li>Mix well and put squid rings, mix again and marinate for one hour or overnight if you like.</li><li>When you're about to cook, in a plastic or freezer bag, mix the ff: flour, baking powder and salt.</li><li>Shake well and start to put inside the squid rings by batches.</li><li>Fry them at once and make sure the oil is hot!</li></ol>",
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 6.053669452667236,
        spoonacularSourceUrl: 'https://spoonacular.com/my-asian-calamari-652825'
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 24,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 3,
        healthScore: 34,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 649.97,
        extendedIngredients: [Array],
        id: 632778,
        title: 'Artisan Farfalle Pasta With Smoked Salmon and Cream Sauce',
        readyInMinutes: 45,
        servings: 2,
        sourceUrl: 'http://www.foodista.com/recipe/KTCQCFSJ/artisan-farfalle-pasta-with-smoked-salmon-and-cream-sauce',
        image: 'https://img.spoonacular.com/recipes/632778-556x370.jpg',
        imageType: 'jpg',
        summary: 'Artisan Farfalle Pasta With Smoked Salmon and Cream Sauce might be just the main course you are searching for. This recipe makes 2 servings with <b>762 calories</b>, <b>28g of protein</b>, and <b>48g of fat</b> each. For <b>$6.5 per serving</b>, this recipe <b>covers 31%</b> of your daily requirements of vitamins and minerals. It is brought to you by Foodista. Only a few people made this recipe, and 3 would say it hit the spot. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. If you have chicken broth, artisan pasta, extra virgin oil, and a few other ingredients on hand, you can make it. Overall, this recipe earns a <b>pretty good spoonacular score of 78%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/farfalle-pasta-with-smoked-salmon-and-cream-cheese-1233493">Farfalle Pasta With Smoked Salmon And Cream Cheese</a>, <a href="https://spoonacular.com/recipes/farfalle-pasta-with-smoked-salmon-and-cream-cheese-30071">Farfalle Pasta With Smoked Salmon And Cream Cheese</a>, and <a href="https://spoonacular.com/recipes/smoked-salmon-and-farfalle-in-lemon-cream-sauce-321798">Smoked Salmon and Farfalle in Lemon Cream Sauce</a>.',
        cuisines: [],
        dishTypes: [Array],
        diets: [Array],
        occasions: [],
        instructions: '<ol><li>In a large pot of boiling salted water, add 85 grams of pasta and cook according to direction about 7 minutes.</li><li>Heat the oil in a saute pan and add the chopped shallots. Cook until transparent, about 2 minutes. Add the wine and the chicken broth and continue to cook for an additional 3-4 minutes until the liquids reduce. Stir in the pesto and sun dried tomatoes. Add the salmon and cream and allow to heat through, about 1-2 minutes.  Serve on the drained cooked pasta.  Serves 2 main courses</li><li>In a large pot of boiling salted water, add 85 grams of pasta and cook according to direction about 7 minutes.</li><li>Heat the oil in a saute pan and add the chopped shallots. Cook until transparent, about 2 minutes.</li><li>Add the wine and the chicken broth and continue to cook for an additional 3-4 minutes until the liquids reduce.</li><li>Stir in the pesto and sun dried tomatoes.</li><li>Add the salmon and cream and allow to heat through, about 1-2 minutes.  Serve on the drained cooked pasta.</li></ol>',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 80.68389892578125,
        spoonacularSourceUrl: 'https://spoonacular.com/artisan-farfalle-pasta-with-smoked-salmon-and-cream-sauce-632778'
      },
      {
        vegetarian: true,
        vegan: false,
        glutenFree: true,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 11,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 3,
        healthScore: 26,
        creditsText: 'foodista.com',
        sourceName: 'foodista.com',
        pricePerServing: 196.78,
        extendedIngredients: [Array],
        id: 657537,
        title: 'Quick and Easy Caprese Salad',
        readyInMinutes: 45,
        servings: 4,
        sourceUrl: 'https://www.foodista.com/recipe/FCD4TQFH/quick-and-easy-caprese-salad',
        image: 'https://img.spoonacular.com/recipes/657537-556x370.jpg',
        imageType: 'jpg',
        summary: 'Need a <b>gluten free, lacto ovo vegetarian, and primal main course</b>? Quick and Easy Caprese Salad could be an awesome recipe to try. One serving contains <b>350 calories</b>, <b>15g of protein</b>, and <b>27g of fat</b>. For <b>$1.97 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. It is brought to you by Foodista. A mixture of balsamic vinegar, basil leaves, bell pepper, and a handful of other ingredients are all it takes to make this recipe so delicious. 3 people found this recipe to be yummy and satisfying. It is an <b>affordable</b> recipe for fans of Mediterranean food. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>good spoonacular score of 74%</b>. Try <a href="https://spoonacular.com/recipes/quick-caprese-salad-551296">Quick Caprese Salad</a>, <a href="https://spoonacular.com/recipes/quick-roasted-tomato-caprese-pasta-salad-673329">Quick Roasted Tomato Caprese Pasta Salad</a>, and <a href="https://spoonacular.com/recipes/easy-caprese-salad-524331">Easy Caprese Salad</a> for similar recipes.',
        cuisines: [Array],
        dishTypes: [Array],
        diets: [Array],
        occasions: [],
        instructions: '<ol><li>Slice mozzarella and tomatoes into 1/4 inch slices and arrange on platter</li><li>Sprinkle basil leaves over all</li><li>Drizzle with oil and vinegar</li><li>Salt and pepper to taste</li></ol>',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 76.59886169433594,
        spoonacularSourceUrl: 'https://spoonacular.com/quick-and-easy-caprese-salad-657537'
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 4,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 11,
        healthScore: 1,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 59.54,
        extendedIngredients: [Array],
        id: 660868,
        title: 'Spanish Meatballs In Tomato Sauce',
        readyInMinutes: 45,
        servings: 20,
        sourceUrl: 'https://www.foodista.com/recipe/B5G2KB4R/spanish-meatballs-in-tomato-sauce',
        image: 'https://img.spoonacular.com/recipes/660868-556x370.jpg',
        imageType: 'jpg',
        summary: `You can never have too many European recipes, so give Spanish Meatballs In Tomato Sauce a try. This recipe serves 20. One serving contains <b>137 calories</b>, <b>6g of protein</b>, and <b>9g of fat</b>. For <b>60 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. 11 person have made this recipe and would make it again. From preparation to the plate, this recipe takes around <b>45 minutes</b>. This recipe from Foodista requires parsley, sandwich bread, salt and pepper, and egg. It works well as a hor d'oeuvre. It is a good option if you're following a <b>dairy free</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 28%</b>. This score is not so tremendous. Try <a href="https://spoonacular.com/recipes/spanish-meatballs-in-tomato-sauce-1399727">Spanish Meatballs In Tomato Sauce</a>, <a href="https://spoonacular.com/recipes/spanish-style-lamb-meatballs-with-spicy-tomato-sauce-620788">Spanish Style Lamb Meatballs with Spicy Tomato Sauce</a>, and <a href="https://spoonacular.com/recipes/spanish-meatballs-with-almond-sauce-553384">Spanish Meatballs with Almond Sauce</a> for similar recipes.`,
        cuisines: [Array],
        dishTypes: [Array],
        diets: [Array],
        occasions: [],
        instructions: '<ol><li>Start by making the tomato sauce.</li><li>Finely chop 1 onion.</li><li>Peel 600g of tomatoes with a serrated peeler. Chop the peeled tomatoes into small pieces.</li><li>Add 2 tablespoons of olive oil in a sauce pan. Add the chopped onions.</li><li>Add a pinch of Pimenton de la Vera (Dulce), which is Spanish smoked sweet paprika. I used 1/4 teaspoon. Add more if you prefer the sauce to be spicy.</li><li>Add the chopped tomatoes to the onions mixture and stir well to combine.</li><li>Add 1 fresh bay leaf. I used 2 dried pieces here because I couldnt find fresh ones.</li><li>Add 1 teaspoon of sugar andd salt and pepper to taste. I added 1/2 teaspoon of salt and 1/4 teaspoon of ground black pepper. Adjust seasoning to taste.</li><li>Cover the sauce pan and reduce the heat to a medium-low and let the tomato mixture simmer gently till it reduces to a sauce like consistency.</li><li></li><li>In the meantime, make the meatballs by adding 1/2 an onion to a food processor.</li><li>Add 2 cloves of garlic. I used 1 tablespoon of minced garlic. Process till the onions and garlic are finely chopped.</li><li>Sweat the onion-garlic mixture in a frying pan with some olive oil. I just realised that I had missed this step. The meatballs still tasted great.</li><li>Add the onion-garlic mixture to 500g ground beef in a mixing bowl.</li><li>Slice off the crust of 4 slices of white bread. Cut the soft white bread into small cubes of 1cm all round.</li><li>Add the chopped bread to the beef mixture.</li><li>Add 2 tablespoons of chopped parsley. Use Italian flat parsley where possible. I couldnt find any, so I used English parsley.</li><li>Add 1 large egg.</li><li>Add salt and pepper to taste. I used approximately 1/4 teaspoon of salt and a pinch of black pepper.</li><li>Mix well to combine.</li><li>Shape the meat mixture into balls that are slightly bigger than the size of a golf ball size. Roll the meat tightly to form meatballs.</li><li>Add 3/4 cup of olive oil to frying pan. The layer of oil should be approximately 3/4cm in the pan.</li><li>Put the pan on medium-high heat and add the meatballs to the oil. Gently roll them around in the oil to brown all surfaces and ensure even cooking.</li><li>When the meatballs are a deep golden brown, remove them from the frying pan and set aside.</li><li>The tomatoes-onion mixture should have reduced to a sauce consistency now. You can use a hand blender to puree the mixture. Or leave the small bits of tomatoes and onions as they are.</li><li>Add the meatballs to the tomato sauce and let the meatballs warm through.</li><li>Garnish with more chopped parsley.</li></ol>',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 30.301916122436523,
        spoonacularSourceUrl: 'https://spoonacular.com/spanish-meatballs-in-tomato-sauce-660868'
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 22,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 60,
        healthScore: 34,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 316.62,
        extendedIngredients: [Array],
        id: 638248,
        title: 'Chicken Piccata With Angel Hair Pasta',
        readyInMinutes: 45,
        servings: 2,
        sourceUrl: 'https://www.foodista.com/recipe/7F7DBP8R/chicken-piccata-with-angel-hair-pasta',
        image: 'https://img.spoonacular.com/recipes/638248-556x370.jpg',
        imageType: 'jpg',
        summary: 'Chicken Piccata With Angel Hair Pasta takes roughly <b>45 minutes</b> from beginning to end. One portion of this dish contains approximately <b>40g of protein</b>, <b>32g of fat</b>, and a total of <b>816 calories</b>. For <b>$3.17 per serving</b>, this recipe <b>covers 34%</b> of your daily requirements of vitamins and minerals. This recipe serves 2. 60 people found this recipe to be yummy and satisfying. A few people really liked this main course. It is brought to you by Foodista. Head to the store and pick up all purpose flour, butter, lemon zest, and a few other things to make it today. Overall, this recipe earns an <b>excellent spoonacular score of 91%</b>. Similar recipes are <a href="https://spoonacular.com/recipes/chicken-piccata-with-angel-hair-pasta-and-asparagus-1000546">chicken piccata with angel hair pastan and asparagus</a>, <a href="https://spoonacular.com/recipes/scallop-piccata-on-angel-hair-696769">Scallop Piccatan on Angel Hair</a>, and <a href="https://spoonacular.com/recipes/angel-hair-pasta-with-chicken-398894">Angel Hair Pasta with Chicken</a>.',
        cuisines: [],
        dishTypes: [Array],
        diets: [],
        occasions: [],
        instructions: '<ol><li>Place  cup of flour in a shallow dish. </li><li>Using a sharp knife, slice chicken breast in half. </li><li>Place a piece of wax paper on top of each piece of chicken and pound with a kitchen mallet until it is about  inch thin.</li><li> Season the chicken well with salt and pepper.  Take the chicken and roll it into the flour, using your fingers to assist in adhering it to the meat. Carefully shake off excess flour. Repeat with second piece of chicken.</li><li>In a large skillet, heat 2 tablespoons olive oil over medium heat. Slide chicken into the skillet and saute on each side until it becomes golden brown, about 3-4 minutes each side. Once chicken is done, transfer to a clean plate and tent with a sheet of aluminum foil.</li><li>Begin boiling the pasta.</li><li>Using the same skillet, add remaining olive oil and saute garlic until it becomes aromatic but not browned. </li><li>Add chili flakes, capers, lemon juice, lemon slices, zest, and chicken broth. </li><li>Use a wooden spoon to scrape off the tasty brown bits from the bottom of the skillet. </li><li>Raise the temperature to medium high heat and allow the liquid to reduce by almost half. </li><li>While the liquid is reducing, use a fork to mash together remaining 1 tablespoon of flour and butter in a small bowl.  Whisk it into the reducing liquid and allow to cook for 1-2 minutes. Be sure to whisk out any lumps of flour. Check for seasonings and adjust with salt/pepper accordingly.</li><li>Drain the cooked pasta. </li><li>Toss the pasta in the lemon caper sauce, tomatoes, and basil, reserving a few spoonfuls of sauce. Check for seasonings and adjust with salt/pepper accordingly.</li><li> Plate pasta and top each with a piece of chicken. Spoon extra lemon caper sauce over the chicken and pasta. Serve immediately.</li></ol>',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 92.24359130859375,
        spoonacularSourceUrl: 'https://spoonacular.com/chicken-piccata-with-angel-hair-pasta-638248'
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 28,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 5,
        healthScore: 24,
        creditsText: 'foodista.com',
        sourceName: 'foodista.com',
        pricePerServing: 231.71,
        extendedIngredients: [Array],
        id: 657377,
        title: 'Pumpkin Ravioli With Browned Butter Sage Sauce',
        readyInMinutes: 45,
        servings: 4,
        sourceUrl: 'https://www.foodista.com/recipe/L3MLJPK3/pumpkin-ravioli-with-browned-butter-sage-sauce',
        image: 'https://img.spoonacular.com/recipes/657377-556x370.jpg',
        imageType: 'jpg',
        summary: 'The recipe Pumpkin Ravioli With Browned Butter Sage Sauce could satisfy your Mediterranean craving in around <b>45 minutes</b>. This recipe makes 4 servings with <b>813 calories</b>, <b>34g of protein</b>, and <b>40g of fat</b> each. For <b>$2.32 per serving</b>, this recipe <b>covers 34%</b> of your daily requirements of vitamins and minerals. 5 people found this recipe to be delicious and satisfying. It works well as a main course. Head to the store and pick up salt, cream, parmesan cheese, and a few other things to make it today. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 56%</b>. This score is good. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/pumpkin-gnocchi-in-browned-butter-sage-sauce-532887">Pumpkin Gnocchi in Browned Butter Sage Sauce</a>, <a href="https://spoonacular.com/recipes/sage-browned-butter-ravioli-423253">Sage & Browned Butter Ravioli</a>, and <a href="https://spoonacular.com/recipes/browned-butter-mushroom-ravioli-with-sage-574170">Browned Butter Mushroom Ravioli with Sage</a>.',
        cuisines: [Array],
        dishTypes: [Array],
        diets: [],
        occasions: [],
        instructions: 'Make dough by mixing egg & sour cream in a bowl, mix in flour until a shaggy rough dough forms, then add splash of milk to make it come together.\n' +
          'Begin mixing & kneading with your hands on a counter top, adding flour until the dough is no longer overly sticky and can be rolled out without tearing or breaking.\n' +
          'Mix all ingredients of the filling together.\n' +
          'Roll out dough to a long thin rectangle.\n' +
          'Along one side of the rectangle, place small scoops of the filling about 1-2 inches apart in a row.\n' +
          'Wet the dough with the water around each scoop of filling.\n' +
          'Take the opposite side of the rectangular dough and fold it over on top of the scoops, then removing as much air from each ravioli as possible, cut into squares or rounds, ensuring each ravioli is sealed thoroughly.\n' +
          'Repeat with the rest of the ravioli.\n' +
          'Cook ravioli in small batches in boiling water for 3 minutes, flip over and boil for another 3 minutes.\n' +
          'Meanwhile, heat a skillet over medium low heat and add butter.\n' +
          "Keep a close eye on the butter, skimming the foam off the top and cooking until it's a golden brown color.\n" +
          'Add sage and stir.\n' +
          'Add boiled ravioli and cook for a few minutes per side.\n' +
          'Serve, topping with a drizzle of the browned butter sauce over top and enjoy!',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 76.56684875488281,
        spoonacularSourceUrl: 'https://spoonacular.com/pumpkin-ravioli-with-browned-butter-sage-sauce-657377'
      },
      {
        vegetarian: true,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 10,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 4,
        healthScore: 0,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 18.61,
        extendedIngredients: [Array],
        id: 649518,
        title: 'Lemon Blondies with Lemon Glaze',
        readyInMinutes: 45,
        servings: 12,
        sourceUrl: 'https://www.foodista.com/recipe/YWCWPNMK/lemon-blondies-with-lemon-glaze',
        image: 'https://img.spoonacular.com/recipes/649518-556x370.jpg',
        imageType: 'jpg',
        summary: 'Lemon Blondies with Lemon Glaze is a <b>lacto ovo vegetarian</b> recipe with 12 servings. For <b>19 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. One serving contains <b>197 calories</b>, <b>2g of protein</b>, and <b>1g of fat</b>. Not a lot of people really liked this side dish. Head to the store and pick up lemon zest, powdered sugar, granulated sugar, and a few other things to make it today. 4 people found this recipe to be flavorful and satisfying. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 12%</b>, which is rather bad. <a href="https://spoonacular.com/recipes/lemon-blondies-with-lemon-glaze-1371859">Lemon Blondies with Lemon Glaze</a>, <a href="https://spoonacular.com/recipes/gluten-free-lemon-poppy-seed-bread-with-honey-lemon-glaze-512695">Gluten Free Lemon Poppy Seed Bread with Honey-Lemon Glaze</a>, and <a href="https://spoonacular.com/recipes/lemon-cornmeal-cake-with-lemon-glaze-and-crushed-blueberry-sauce-238783">Lemon Cornmeal Cake with Lemon Glaze and Crushed-Blueberry Sauce</a> are very similar to this recipe.',
        cuisines: [],
        dishTypes: [Array],
        diets: [Array],
        occasions: [],
        instructions: '<ol><li>Preheat oven to 350 degrees.  Spray an 8 or 9-inch square pan with nonstick cooking spray.  In a medium bowl, stir together flour and salt.  Using an electric mixer, cream the butter, sugar and lemon zest at medium speed until light and fluffy.  Add eggs, 1 at a time, beating well after each addition.  Stir in 2 tablespoons lemon juice.  Reduce speed to low and add flour mixture, mixing until incorporated.  Spread batter into prepared pan and bake for about 30-35 minutes, or until toothpick inserted in center comes out clean.  Cool on wire rack to room temperature.</li><li>Meanwhile, make the glaze by combining the powdered sugar, lemon juice and zest in a small bowl.  Spread over brownies and let set for at least 10 minutes before serving.</li></ol>',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 14.97658634185791,
        spoonacularSourceUrl: 'https://spoonacular.com/lemon-blondies-with-lemon-glaze-649518'
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 4,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 5,
        healthScore: 4,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 39.11,
        extendedIngredients: [Array],
        id: 640907,
        title: 'Croissants With Sesame Seeds (Kifli)',
        readyInMinutes: 45,
        servings: 50,
        sourceUrl: 'https://www.foodista.com/recipe/QBPWT3WS/croissants-with-sesame-seeds-kifli',
        image: 'https://img.spoonacular.com/recipes/640907-556x370.jpg',
        imageType: 'jpg',
        summary: `The recipe Croissants With Sesame Seeds (Kifli) could satisfy your Southern craving in roughly <b>45 minutes</b>. This recipe makes 50 servings with <b>135 calories</b>, <b>4g of protein</b>, and <b>7g of fat</b> each. For <b>39 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. 5 people have tried and liked this recipe. It works well as a hor d'oeuvre. This recipe from Foodista requires milk, active yeast, vegetable oil, and flour. Taking all factors into account, this recipe <b>earns a spoonacular score of 26%</b>, which is rather bad. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/croissants-with-sesame-seeds-and-feta-cheese-macedonian-cheese-rolls-kifli-566274">Croissants with Sesame Seeds and Feta Cheese – Macedonian Cheese Rolls – Kifli</a>, <a href="https://spoonacular.com/recipes/vegan-croissants-posni-kifli-664428">Vegan Croissants - Posni Kifli</a>, and <a href="https://spoonacular.com/recipes/honey-teriyaki-chicken-fingers-with-sesame-seeds-with-sesame-cellophane-noodles-and-snap-peas-351353">Honey-Teriyaki Chicken Fingers with Sesame Seeds with Sesame Cellophane Noodles and Snap Peas</a>.`,
        cuisines: [Array],
        dishTypes: [Array],
        diets: [],
        occasions: [],
        instructions: 'In a large, deep mixing bowl pour in lukewarm milk.\n' +
          'Stir in the sugar, 2 tablespoons of flour, and the yeast.\n' +
          'Let stand for ten minutes.\n' +
          'Add in the baking powder, salt, vegetable oil, egg whites, and 6 cups of flour.\n' +
          'Stir with a wooden spoon until the mixture is well incorporated, you may need to get your hands in there towards the end, and then bring the dough to a lightly floured surface.\n' +
          'Knead the dough for 10 minutes.\n' +
          'Put the dough in a large bowl, cover it, and let it stand for one hour.\n' +
          'Preheat oven at 375.\n' +
          'Bring the dough back to your working area and knead it again for another 5 minutes. You want to make sure that all those air bubbles are out.\n' +
          'Form the dough into a log and cut it into 5 or 6 equal pieces.\n' +
          'Take one piece (cover the rest with a kitchen towel), and roll it out to a size as big as a medium pizza.\n' +
          'With a knife, cut the rolled out dough into 8 equal slices.\n' +
          'Beginning at the widest point of the slice start rolling it towards the narrowest point.\n' +
          'Place the croissants on a lightly greased baking sheet.\n' +
          'Continue to do this with the rest of the dough.\n' +
          'In a small mixing bowl, whisk the 4 egg yolks.\n' +
          'Brush each croissant with the egg yolk.\n' +
          'Top each croissant with sesame seeds.\n' +
          'Put 4 or 5 small pieces of margarine throughout the baking sheet.\n' +
          'Bake for  15 to 20 minutes, or until golden brown.\n' +
          'Cover with a kitchen towel while they are cooling.\n' +
          'Serve immediately or store in an airtight container.',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 44.16646194458008,
        spoonacularSourceUrl: 'https://spoonacular.com/croissants-with-sesame-seeds-kifli-640907'
      },
      {
        vegetarian: false,
        vegan: false,
        glutenFree: false,
        dairyFree: false,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 26,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 17,
        healthScore: 2,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 124.7,
        extendedIngredients: [Array],
        id: 642259,
        title: 'Eggless Blueberry and White Chocolate Baked Cheesecake',
        readyInMinutes: 90,
        servings: 12,
        sourceUrl: 'https://www.foodista.com/recipe/2GX8Y2ZP/eggless-blueberry-and-white-chocolate-baked-cheesecake',
        image: 'https://img.spoonacular.com/recipes/642259-556x370.jpg',
        imageType: 'jpg',
        summary: 'The recipe Eggless Blueberry and White Chocolate Baked Cheesecake can be made <b>in about 1 hour and 30 minutes</b>. This recipe makes 12 servings with <b>587 calories</b>, <b>11g of protein</b>, and <b>37g of fat</b> each. For <b>$1.25 per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. A mixture of vanillan extract, ricotta cheese, lemon juice, and a handful of other ingredients are all it takes to make this recipe so delicious. A couple people really liked this dessert. 17 people were glad they tried this recipe. It is brought to you by Foodista. With a spoonacular <b>score of 24%</b>, this dish is not so great. Similar recipes include <a href="https://spoonacular.com/recipes/eggless-blueberry-and-white-chocolate-baked-cheesecake-1433451">Eggless Blueberry and White Chocolate Baked Cheesecake</a>, <a href="https://spoonacular.com/recipes/white-chocolate-blueberry-cheesecake-543349">White Chocolate Blueberry Cheesecake</a>, and <a href="https://spoonacular.com/recipes/blueberry-and-white-chocolate-cheesecake-51501">Blueberry And White Chocolate Cheesecake</a>.',
        cuisines: [],
        dishTypes: [Array],
        diets: [],
        occasions: [],
        instructions: '<ol><li>Method for the base:</li><li>Combine the crushed digestive biscuits with the melted butter and mix thoroughly.</li><li>Firmly press the mixture into a greased 10 inch springform tin.</li><li>Method for the filling:</li><li>Beat together all of the ingredients (excluding the blueberries) until it has thickened. Kurma suggests not to overmix this.</li><li>Pour  of the mixture on top of the crust and scatter on the blueberries. Pour the rest of the cheese mixture over the blueberries. This method protects the blueberries from burning in the oven and the flour they are dusted in will stop them from sinking to the bottom of the cheesecake during cooking.</li><li>Bake at 180 degrees Celsius for 1  hours until set (I left mine for 1 hour because my fan oven cooks things a little quicker).</li><li>Allow to cool and refrigerate for at least 8 hours.</li><li>Cut into (extra) large wedges and serve.</li></ol>',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 36.15742492675781,
        spoonacularSourceUrl: 'https://spoonacular.com/eggless-blueberry-and-white-chocolate-baked-cheesecake-642259'
      },
      {
        vegetarian: true,
        vegan: true,
        glutenFree: true,
        dairyFree: true,
        veryHealthy: false,
        cheap: false,
        veryPopular: false,
        sustainable: false,
        lowFodmap: false,
        weightWatcherSmartPoints: 3,
        gaps: 'no',
        preparationMinutes: -1,
        cookingMinutes: -1,
        aggregateLikes: 18,
        healthScore: 18,
        creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
        license: 'CC BY 3.0',
        sourceName: 'Foodista',
        pricePerServing: 64.81,
        extendedIngredients: [Array],
        id: 642660,
        title: 'Fennel and Orange Salad With Toasted Hazelnuts and Cranberries',
        readyInMinutes: 45,
        servings: 4,
        sourceUrl: 'https://www.foodista.com/recipe/4J3YBFD6/fennel-and-orange-salad-with-toasted-hazelnuts-and-cranberries',
        image: 'https://img.spoonacular.com/recipes/642660-556x370.jpg',
        imageType: 'jpg',
        summary: `The recipe Fennel and Orange Salad With Toasted Hazelnuts and Cranberries can be made <b>in about 45 minutes</b>. This recipe serves 4 and costs 65 cents per serving. One serving contains <b>167 calories</b>, <b>2g of protein</b>, and <b>12g of fat</b>. A mixture of navel orange, cranberries, white-wine vinegar, and a handful of other ingredients are all it takes to make this recipe so tasty. It works well as a hor d'oeuvre. 18 people were impressed by this recipe. <b>Christmas</b> will be even more special with this recipe. It is a good option if you're following a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian</b> diet. It is brought to you by Foodista. With a spoonacular <b>score of 68%</b>, this dish is pretty good. <a href="https://spoonacular.com/recipes/baby-spinach-salad-with-pears-red-onions-cranberries-and-toasted-hazelnuts-201726">Baby Spinach Salad with Pears, Red Onions, Cranberries and Toasted Hazelnuts</a>, <a href="https://spoonacular.com/recipes/blood-orange-salad-with-shaved-fennel-and-hazelnuts-51144">Blood Orange Salad With Shaved Fennel And Hazelnuts</a>, and <a href="https://spoonacular.com/recipes/fennel-orange-salad-with-toasted-pistachios-43207">Fennel & Orange Salad With Toasted Pistachios</a> are very similar to this recipe.`,
        cuisines: [],
        dishTypes: [Array],
        diets: [Array],
        occasions: [Array],
        instructions: 'Finely grate enough zest from the orange to measure 1/2 tablespoon. Cut peel, including all white pith, from the orange with a paring knife. Then cut segments free from membranes.\n' +
          'Cut out and discard core of fennel bulb, then cut bulbs crosswise into very thin slices, as thin as you can get them.\n' +
          'Whisk together vinegar, zest, salt, and pepper in a small bowl until salt is dissolved, then add olive oil slowly in a stream, whisking until combined well.\n' +
          'Toast hazelnuts on medium heat on a dry skillet.\n' +
          'Toss fennel and oranges with vinaigrette in a large bowl until combined well.\n' +
          'Top with toasted hazelnuts and dried cranberries. Garnish with a few fennel fronds.',
        analyzedInstructions: [Array],
        originalId: null,
        spoonacularScore: 77.57572937011719,
        spoonacularSourceUrl: 'https://spoonacular.com/fennel-and-orange-salad-with-toasted-hazelnuts-and-cranberries-642660'
      }
    ]
  }