import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';

import { PinkThemeProvider } from '@workspace/components';

export const metadata = {
  title: 'Welcome to plan-my-plate',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <PinkThemeProvider>{children}</PinkThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
