export type CuisineType =
  | 'african'
  | 'asian'
  | 'american'
  | 'british'
  | 'cajun'
  | 'caribbean'
  | 'chinese'
  | 'eastern european'
  | 'european'
  | 'french'
  | 'german'
  | 'greek'
  | 'indian'
  | 'irish'
  | 'italian'
  | 'japanese'
  | 'jewish'
  | 'korean'
  | 'latin american'
  | 'mediterranean'
  | 'mexican'
  | 'middle eastern'
  | 'nordic'
  | 'southern'
  | 'spanish'
  | 'thai'
  | 'vietnamese';