export const mockRecipes = {
  recipes: [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: true,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 24,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 3,
      healthScore: 12,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 260.37,
      extendedIngredients: [Array],
      id: 652825,
      title: 'My Asian Calamari',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: 'https://www.foodista.com/recipe/T64CXDRZ/my-asian-calamari',
      image: 'https://img.spoonacular.com/recipes/652825-556x370.jpg',
      imageType: 'jpg',
      summary: `My Asian Calamari requires around <b>45 minutes</b> from start to finish. Watching your figure? This dairy free and pescatarian recipe has <b>563 calories</b>, <b>24g of protein</b>, and <b>5g of fat</b> per serving. For <b>$2.6 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. This recipe is typical of Asian cuisine. A mixture of all spice powder, cornstarch, squid rings, and a handful of other ingredients are all it takes to make this recipe so delicious. 3 people have made this recipe and would make it again. It works well as a rather inexpensive hor d'oeuvre. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 59%</b>, which is solid. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/asian-calamari-salad-586727">Asian Calamari Salad</a>, <a href="https://spoonacular.com/recipes/southeast-asian-rice-noodles-with-calamari-and-herbs-188585">Southeast Asian Rice Noodles with Calamari and Herbs</a>, and <a href="https://spoonacular.com/recipes/christmas-eve-calamari-calamari-in-umido-per-la-vigilia-di-natale-597284">Christmas Eve Calamari | Calamari in Umido per la Vigilia di Natale</a>.`,
      cuisines: [Array],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      instructions:
        "<ol><li>In a bowl mix the ff: salt, sugar, pepper,egg white, curry powder,all spice and cornstarch.</li><li>Mix well and put squid rings, mix again and marinate for one hour or overnight if you like.</li><li>When you're about to cook, in a plastic or freezer bag, mix the ff: flour, baking powder and salt.</li><li>Shake well and start to put inside the squid rings by batches.</li><li>Fry them at once and make sure the oil is hot!</li></ol>",
      analyzedInstructions: [Array],
      originalId: null,
      spoonacularScore: 6.053669452667236,
      spoonacularSourceUrl: 'https://spoonacular.com/my-asian-calamari-652825',
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 24,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 3,
      healthScore: 34,
      creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
      license: 'CC BY 3.0',
      sourceName: 'Foodista',
      pricePerServing: 649.97,
      extendedIngredients: [Array],
      id: 632778,
      title: 'Artisan Farfalle Pasta With Smoked Salmon and Cream Sauce',
      readyInMinutes: 45,
      servings: 2,
      sourceUrl:
        'http://www.foodista.com/recipe/KTCQCFSJ/artisan-farfalle-pasta-with-smoked-salmon-and-cream-sauce',
      image: 'https://img.spoonacular.com/recipes/632778-556x370.jpg',
      imageType: 'jpg',
      summary:
        'Artisan Farfalle Pasta With Smoked Salmon and Cream Sauce might be just the main course you are searching for. This recipe makes 2 servings with <b>762 calories</b>, <b>28g of protein</b>, and <b>48g of fat</b> each. For <b>$6.5 per serving</b>, this recipe <b>covers 31%</b> of your daily requirements of vitamins and minerals. It is brought to you by Foodista. Only a few people made this recipe, and 3 would say it hit the spot. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. If you have chicken broth, artisan pasta, extra virgin oil, and a few other ingredients on hand, you can make it. Overall, this recipe earns a <b>pretty good spoonacular score of 78%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/farfalle-pasta-with-smoked-salmon-and-cream-cheese-1233493">Farfalle Pasta With Smoked Salmon And Cream Cheese</a>, <a href="https://spoonacular.com/recipes/farfalle-pasta-with-smoked-salmon-and-cream-cheese-30071">Farfalle Pasta With Smoked Salmon And Cream Cheese</a>, and <a href="https://spoonacular.com/recipes/smoked-salmon-and-farfalle-in-lemon-cream-sauce-321798">Smoked Salmon and Farfalle in Lemon Cream Sauce</a>.',
      cuisines: [],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      instructions:
        '<ol><li>In a large pot of boiling salted water, add 85 grams of pasta and cook according to direction about 7 minutes.</li><li>Heat the oil in a saute pan and add the chopped shallots. Cook until transparent, about 2 minutes. Add the wine and the chicken broth and continue to cook for an additional 3-4 minutes until the liquids reduce. Stir in the pesto and sun dried tomatoes. Add the salmon and cream and allow to heat through, about 1-2 minutes.  Serve on the drained cooked pasta.  Serves 2 main courses</li><li>In a large pot of boiling salted water, add 85 grams of pasta and cook according to direction about 7 minutes.</li><li>Heat the oil in a saute pan and add the chopped shallots. Cook until transparent, about 2 minutes.</li><li>Add the wine and the chicken broth and continue to cook for an additional 3-4 minutes until the liquids reduce.</li><li>Stir in the pesto and sun dried tomatoes.</li><li>Add the salmon and cream and allow to heat through, about 1-2 minutes.  Serve on the drained cooked pasta.</li></ol>',
      analyzedInstructions: [Array],
      originalId: null,
      spoonacularScore: 80.68389892578125,
      spoonacularSourceUrl:
        'https://spoonacular.com/artisan-farfalle-pasta-with-smoked-salmon-and-cream-sauce-632778',
    },
    {
      vegetarian: true,
      vegan: false,
      glutenFree: true,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      lowFodmap: false,
      weightWatcherSmartPoints: 11,
      gaps: 'no',
      preparationMinutes: -1,
      cookingMinutes: -1,
      aggregateLikes: 3,
      healthScore: 26,
      creditsText: 'foodista.com',
      sourceName: 'foodista.com',
      pricePerServing: 196.78,
      extendedIngredients: [Array],
      id: 657537,
      title: 'Quick and Easy Caprese Salad',
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        'https://www.foodista.com/recipe/FCD4TQFH/quick-and-easy-caprese-salad',
      image: 'https://img.spoonacular.com/recipes/657537-556x370.jpg',
      imageType: 'jpg',
      summary:
        'Need a <b>gluten free, lacto ovo vegetarian, and primal main course</b>? Quick and Easy Caprese Salad could be an awesome recipe to try. One serving contains <b>350 calories</b>, <b>15g of protein</b>, and <b>27g of fat</b>. For <b>$1.97 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. It is brought to you by Foodista. A mixture of balsamic vinegar, basil leaves, bell pepper, and a handful of other ingredients are all it takes to make this recipe so delicious. 3 people found this recipe to be yummy and satisfying. It is an <b>affordable</b> recipe for fans of Mediterranean food. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>good spoonacular score of 74%</b>. Try <a href="https://spoonacular.com/recipes/quick-caprese-salad-551296">Quick Caprese Salad</a>, <a href="https://spoonacular.com/recipes/quick-roasted-tomato-caprese-pasta-salad-673329">Quick Roasted Tomato Caprese Pasta Salad</a>, and <a href="https://spoonacular.com/recipes/easy-caprese-salad-524331">Easy Caprese Salad</a> for similar recipes.',
      cuisines: [Array],
      dishTypes: [Array],
      diets: [Array],
      occasions: [],
      instructions:
        '<ol><li>Slice mozzarella and tomatoes into 1/4 inch slices and arrange on platter</li><li>Sprinkle basil leaves over all</li><li>Drizzle with oil and vinegar</li><li>Salt and pepper to taste</li></ol>',
      analyzedInstructions: [Array],
      originalId: null,
      spoonacularScore: 76.59886169433594,
      spoonacularSourceUrl:
        'https://spoonacular.com/quick-and-easy-caprese-salad-657537',
    },
  ],
};
